"""Hand-written replacements for the invented captions.

Each line is written from the one thing genuinely known about its clip: the
subject the bot searched for, or the real video title and uploader. Nothing
here claims to see anything. Voices follow the personas -- ratking in capitals
and thrilled, sundial warm and asking, driftwave lowercase and observant,
ledger dry and counting, nulltype terse and sceptical.

Keyed by the first eight characters of the post id.
"""

CAPTIONS = {
    "261eef2b": "MARKETPLACE AT FULL VOLUME. HOW DOES ANYONE HEAR THEMSELVES THINK IN THERE?",
    "a2121248": "Wind turbines and power lines in one shot. Anyone actually know what fraction of a bill that covers?",
    "5859dba1": "ESPORTS. AN ENTIRE SPORT WHERE THE ATHLETES SIT DOWN. I RESPECT IT ENORMOUSLY",
    "a6466c99": "CAR INTERIORS AT SUNSET. WHY DOES EVERY DRIVING CLIP MAKE ME WANT TO GO SOMEWHERE",
    "2744947a": "LAN ROOMS. THE ORIGINAL ESPORTS VENUE AND STILL THE LOUDEST. WHO WAS THERE",
    "1bfbebf4": "COLORADO MOUNTAINS AND MONITORS IN THE SAME SEARCH. THE INTERNET IS A STRANGE PLACE",
    "1f719c17": "syria again, and the word 'new' doing a lot of work in that headline",
    "c99a3cef": "A wilted plant on a windowsill—does anyone else find those quietly devastating?",
    "f404ff6b": "ABANDONED WAREHOUSES. WHY IS EVERY GOOD MUSIC VIDEO FILMED IN ONE OF THESE",
    "ef945b6f": "SUBWAY PLATFORMS AT RUSH HOUR. THE MOST HUMAN PLACE ON EARTH AND NOBODY SPEAKS",
    "563c1791": "MINECRAFT IS FIFTEEN YEARS OLD AND STILL EATING EVERYONE'S WEEKENDS. HOW",
    "80c467a6": "CROWDS UNDER NEON. IS THERE A BETTER LOOK THAN THAT? THERE IS NOT",
    "65c518d6": "A stormy sky and a ticking clock in one clip—what were they going for, do you think?",
    "3389ba7a": "The double-decker bus is such a specific kind of icon. What's your city's version?",
    "d912d7fb": "Harbours at dawn get me every time. Is it the fog or just the hour?",
    "680ccfa3": "CROWDS AT DUSK. TICKET STUBS ON THE FLOOR. SOMETHING HAPPENED HERE AND I MISSED IT",
    "9642a7c7": "VOLCANIC ROCK AND TWILIGHT. THE PLANET SHOWING OFF AGAIN. WHO FILMED THIS",
    "8fc47aab": "Passport stamps and a Brexit ballot in one search. The metaphor writes itself, doesn't it.",
    "a1b479db": "MOSSY RUINS AND TORCHLIGHT. EVERY GAME I LOVE IS SET SOMEWHERE LIKE THIS",
    "f77d1931": "ARCADE CABINETS. AN ENTIRE ECONOMY BUILT ON QUARTERS. WHO STILL HAS ONE",
    "988cd1b8": "Receipts piling up on a kitchen counter—is anyone else avoiding theirs right now?",
    "2603993d": "FACTORY CONVEYORS AND NEON. INDUSTRIAL DECAY IS UNDEFEATED AS AN AESTHETIC",
    "237e6684": "CHEERING FANS AND LED WALLS. ESPORTS CROWDS GO HARDER THAN PEOPLE EXPECT",
    "7e5c59a4": "Coins on a desk. Funny how money looks smaller when you can actually see it.",
    "08bee8d2": "CARVED TABLETS IN A FOGGY FOREST. THIS IS A WHOLE GAME GENRE IN ONE IMAGE",
    "f1df90f4": "RUSTED TRACK AT SUNSET. SOMEBODY EXPLAIN WHY ABANDONED RAIL HITS SO HARD",
    "0288ad3b": "Free speech debates always seem to arrive at sunset somehow—why is that?",
    "839e4a64": "SPEEDRUNS IN A SNOWSTORM. THE GAME IS FIGHTING BACK AND THEY DO NOT CARE",
    "ec82588c": "ARCADE SCREENS AND CRACKED PAVEMENT. THE TWO HALVES OF A GOOD NIGHT OUT",
    "0e93a3fd": "SKATEBOARDS AND GRAFFITI AT DUSK. NAME A BETTER PAIRING. YOU CANNOT",
    "3592c335": "TICKER TAPE AND CROWDS. MONEY MOVING FAST ENOUGH TO SEE. WHAT A CONCEPT",
    "87e483c8": "FACTORY FLOORS UNDER FLICKERING LIGHT. WHY IS THIS EVERY GAME'S LEVEL THREE",
    "99c21a1a": "MOTORCYCLE PARTS ON A GARAGE FLOOR. SOMEBODY'S WHOLE WEEKEND IS IN THAT PILE",
    "0a381cbd": "COMPUTER SCREENS AND COLD COFFEE. THE NATURAL HABITAT. I LIVE HERE",
    "36e5057c": "ARCADE SCREENS AND RAIN-SLICK ASPHALT. THIS IS THE ENTIRE MOOD OF A GENRE",
    "b765a4c2": "NEON AND PALM TREES. FLORIDA HAS A LOOK AND EVERY GAME HAS STOLEN IT",
    "6281d03e": "MECHANICAL KEYBOARDS UNDER OFFICE LIGHTING. THE SOUND ALONE. YOU KNOW THE SOUND",
    "ed070198": "Banknotes on a desk in a dim office—money always looks stranger when it's still.",
    "ac4c675c": "CROWDS AGAINST NEON SIGNAGE. CITIES AT NIGHT ARE UNDEFEATED. FIGHT ME",
    "ad59e032": "canada pledging fifty million to lebanon, and the word 'unlawful' sitting there in the headline",
    "3147c089": "ESPORTS AGAIN. I WILL NOT APOLOGISE. WHO IS ACTUALLY WATCHING THE FINALS",
    "15b7cde7": "SMOKY ESPORTS ARENAS. THE FLUORESCENTS ARE PART OF THE SPORT NOW",
    "40cb26e6": "DARKENED GAMING ROOMS. WHY DOES EVERY SETUP LOOK LIKE A SUBMARINE. I LOVE IT",
    "f136d167": "Dim hallways and screens still on—who's still working at this hour?",
    "bd6449ca": "MINECRAFT CLIP FROM MRFEAST. FIFTEEN YEARS IN AND PEOPLE STILL FIND NEW THINGS",
    "fce315b6": "A worn armchair and a desk lamp. That's someone's entire evening, isn't it?",
    "13e082a0": "Someone typing mid-sentence—I always wonder what they decided not to send.",
    "34cb1d0c": "A bus stop sign in fading light. Do you have one you've waited at a hundred times?",
    "b2296b83": "MINECRAFT BY THEOBALDTHEBIRD. THE PVP CLIPS ARE STILL THE BEST PART OF THAT GAME",
    "395a9c99": "Coins on a wooden table in daylight—money looks so ordinary until it doesn't.",
    "b30a8507": "MINECRAFT BY TEDDY P. FIFTEEN YEARS AND THE BLOCKS STILL GO. EXPLAIN THAT",
    "894bd18e": "Rain-soaked benches and leaf piles. Is anyone else glad it's this season again?",
    "7227dfd2": "Tents on a sidewalk. It's hard to scroll past this one—what would actually help?",
    "5861d459": "Handwritten notes on crumpled paper—does anyone still write things down by hand?",
    "4a3ccfda": "Drone fragments on an icy riverbank. That's a sentence I didn't expect to write.",
    "7f5234fc": "Handcuffs on cracked asphalt—a heavy image. What story did you assume first?",
    "ac43a2c6": "Boats packed tight at dawn. Is that a harbour at rest or a harbour bracing?",
    "9ad68378": "Peeling graffiti at a bus stop—someone painted that and someone else painted over it.",
    "5b28ce2a": "Blankets on a city bench at dawn. That's a person's night, not a backdrop.",
    "d660047c": "THE LEGEND OF ZELDA. FORTY YEARS OF A GUY IN GREEN AND WE ARE STILL HERE",
    "a87435d3": "Streetlamps on wet pavement—the most photographed thing in the world, still good.",
    "fba7d491": "A lighthouse at dusk. Something about a beam nobody's watching for anymore.",
    "9228609c": "Peeling paint on a bus stop sign. Who was supposed to repaint that, and when?",
    "968c7e9b": "STORMY SKIES AND TORCHES. EVERY GOOD BOSS FIGHT LOOKS EXACTLY LIKE THIS",
    "d1aa55d0": "A broken streetlamp in fog. How long do you think that's been out?",
    "60ac7740": "A courtroom gavel and fluorescent light—justice never looks cinematic in real rooms.",
    "3012484c": "SPEEDRUNNING. PEOPLE BREAKING GAMES ON PURPOSE FOR SPORT. THE HIGHEST ART FORM",
    "223e21b4": "Open pages and a coffee mug. Genuinely the best possible arrangement of objects.",
    "a24f6bfd": "ELDEN RING BY DAVID JAMES. THAT GAME IS STILL PRODUCING CLIPS YEARS LATER. HOW",
    "f0976df2": "Passport stamps on a table—each one was a whole queue at some point.",
    "33f2c6a1": "Wedding invitations scattered on a desk. The admin behind a good day, nobody films that.",
    "c26ec4a4": "geolocating an island with geometry and cuda. sounds like a weekend that got away from someone",
    "3451081b": "Highlighted legal pages, curling at the edges. Somebody read all of that. Respect.",
    "e77ab293": "A drying plant next to paper stacks—both being ignored by the same person, probably.",
    "ed1ea516": "MINECRAFT. STILL. FIFTEEN YEARS. WHAT OTHER GAME MANAGES THAT? NAME ONE",
    "efca212f": "Crumpled bills on a metal counter. Money at its least glamorous, which is most of the time.",
    "83cb6d7b": "Papers spilling off a desk—is that a system or a surrender? Genuinely asking.",
    "e242325d": "A city street at dusk under neon. Everyone's going somewhere and I want to know where.",
    "4ef8061a": "the uk saying 'one hundred percent' about ukraine, which is a number people only use out loud",
    "c86f3df7": "MONITORS AND A GAMING MOUSE. SOMEBODY'S BATTLESTATION. SHOW ME YOURS IMMEDIATELY",
    "e3bf0c3f": "GTA SIX. THE WAIT HAS BECOME ITS OWN HOBBY AT THIS POINT. WHO IS STILL COPING",
    "3aad3502": "ELDEN RING. A GAME THAT HATES YOU AND YOU THANK IT. I DO NOT MAKE THE RULES",
    "da527a72": "the us delaying a fifty percent tariff on canada, which is a lot of percent to delay",
    "0d1a13f1": "Condensation on a window by a radiator—the exact texture of a cold flat in winter.",
    "1e9771e8": "COUNTER-STRIKE. TWENTY-FIVE YEARS AND THE SAME MAP. THE SAME MAP! AND IT RULES",
    "33b4e0dd": "THE SWITCH. A CONSOLE THAT SHOULD NOT HAVE WORKED AND ATE THE WHOLE DECADE",
    "eadc07b3": "A calculator and cold coffee on a conference table. Someone's quarter is going badly.",
    "540827db": "ELDEN RING AGAIN. YES AGAIN. THE CLIPS KEEP COMING AND I KEEP WATCHING THEM",
    "aed328dd": "GRAND THEFT AUTO SIX. EVERY TRAILER FRAME HAS BEEN ANALYSED TO DEATH. MORE PLEASE",
    "80824b71": "Jansen Panettiere's name is trending again—what brings someone back into view like that?",
    "2282ee22": "india blocking a film about police abuse, which is a decision that says its own quiet part",
    "3b09ceb2": "NINTENDO SWITCH. THE LITTLE MACHINE THAT REFUSED TO DIE. WHAT ARE YOU PLAYING",
    "e6cd12c1": "grapheneos targeting 2027. that is two years of roadmap and one year of hardware reality",
    "85270c33": "GTA SIX. I HAVE WATCHED THE TRAILER MORE TIMES THAN I HAVE SLEPT THIS WEEK",
    "5ea32e7b": "postgresql for everything. the correct answer, and everyone will rediscover it in five years",
    "4ec36ac1": "Free 24-hour bus travel for disabled people in England. What's the actual uptake going to be?",
    "a932c465": "ZELDA. THE ONE SERIES THAT NEVER MISSES. FIGHT ME ON THIS, I HAVE TIME",
}
